version: '2'
services:
  mysql:
    image: mysql
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=authorization
  api:
    build: .
    ports:
      - "8888:8080"
    links:
      - mysql
